name: deployment 
on: 
    push: 
        branches: [test]
jobs:
    push-to-docker:
        name: continuous integration
        runs-on: ubuntu-latest
        steps:
            - name: checkout from repo
              uses: actions/checkout@v4

            - name: login to dockerhub
              uses: docker/login-action@v3
              with: 
                username: ${{secrets.DOCKER_USER}}
                password: ${{secrets.PASSWORD}}
                
            - name: build & push docker image
              uses: docker/build-push-action@v4
              with: 
                context: ./
                push: true
                tags: ernieboa6/nasrepotest:v1    
